### PR TITLE
Accordion

### PR DESCRIPTION
**Pull request by cutandpastey**

### CODE REVIEW

**Comment by jamespamplin** [comment]
Can we have a gif?

**Comment by cutandpastey** [comment]
You could always run the application?

**Comment by jamespamplin** [comment]
@cutandpastey Indeed...... will give it a go.

From the code - is this a horizontal accordion? Would be good to make that explicit in the code. No need to support vertical for now though.

**Comment by theefer** [comment]
Would be nice to always have screenshots for UI PRs as a rule though?

**Comment by cutandpastey** [comment]
The whole point of the app is that it's self documenting. It takes five mins to setup and after that you can actually use the UI. Screenshots and GIF's are a poor man's way of reviewing when things are interactive, also CSS sometimes (especially using `:before` & `:after`)needs to be inspected in the dev tools.

**Comment by rrees** [comment]
Running the app is fine for devs and the current state of the application but it would be nice to have a visual indication about the component in its state at the time of the PR submission and for people who don't want to learn how to run the app to see what is happening in the project.

**Comment by sihil** [comment]
Agree with @rrees et al here.

**Comment by jamespamplin** [comment]
Running locally - this looks like a "tabbed" interface to me really, as I can only see 1 child at a time. For an "accordion" I was expecting to see something like: http://jqueryui.com/accordion/

**Comment by robinedman** [comment]
:+1: 

Opening issues for outstanding issues.

**Comment by hmgibson23** [comment]
:+1:  - we're going to make issues for the outstanding things on this PR

**Pull request merged**
