### PR TITLE
Add a start script

### PR DESCRIPTION
**Pull request by piuccio**
Tiny change to allow deploy on heroku.

Just an experiment to address #31 
Heroku has hooks so that every time you create a PR it deploys your app to a new container, however I'm not an Admin in GH so I can't set up the hook.

The app is running on `https://tools-components.herokuapp.com/`

### CODE REVIEW

**Comment by cutandpastey** [comment]
@piuccio This is Awesome! One question I have is about the deploy step. How did you get the built css onto heroku, deploy dist?

**Comment by piuccio** [comment]
I followed this [heroku guide](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction).

In short

```
heroku login
heroku create
git push heroku master
```

Every time I push master to the heroku remote, the code is deployed, `npm start` gets called and you can access the internal web server.

To deploy again on heroku I need to push again master to heroku or set up github hooks.
@robertberry helped setting up hooks for [facia-tool-node-api](https://github.com/guardian/facia-tool-node-api) so that every time anyone pushes to master, the code gets deployed to heroku.

**Comment by cutandpastey** [comment]
Okay, but the built .css files are ignored in master. When I view the app on heroku, I see css. Where does it come from? Also, we might want to hook this up to CI. @sihil can RiffRaff deploy to heroku? If not we can write a script similar to `bin/release-cli` which deploys or just deploy to heroku in that actual script?

**Comment by piuccio** [comment]
Heroku runs `npm install && npm start` as part of the deploy. `install` calls `npm run build-sass` which generates the css on the heroku box.

If we setup webhooks there's no need for riffraff to deploy to heroku. The latter will automatically deploy once we push to master (or we create a PR).

**Comment by cutandpastey** [comment]
:+1:

**Pull request merged**
