### PR TITLE
Error Bars

### PR DESCRIPTION
**Pull request by cutandpastey**
Error bar components to replace the ones in composer.

screen shot 2015-06-23 at 15 00 41
screen shot 2015-06-23 at 15 00 47

### CODE REVIEW

**Comment by robinedman** [comment]
More of a design question but yellow says "warning" rather than error to me. Would it be better to keep a red colour? @akemitakagi @alastairjardine

**Comment by cutandpastey** [comment]
@robinedman If you look through the source you will see the yellow option is defined as a warning.

**Comment by akemitakagi** [comment]
Yellow is for used for warning.
Which context are you referring to?

On 23 June 2015 at 15:07, Robin Edman notifications@github.com wrote:

> More of a design question but yellow says "warning" rather than error to
> me. Would it be better to keep a red colour? @akemitakagi
> https://github.com/akemitakagi @alastairjardine
> https://github.com/alastairjardine
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/tools-components/pull/33#issuecomment-114517928
> .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by robinedman** [comment]
Ah, my bad. I was looking at the image and the message there

**Comment by cutandpastey** [comment]
ping @robinedman @jamespamplin

**Comment by sihil** [comment]
I'm with @robinedman! The fact that the message says 'error' but is a warning.

Can I clarify if the top one is the old one and the bottom is the new one? Or is the top and error and the bottom a warning? If so - I find the pastel/solid colour choices for the two a little weird. The warning is more dramatic than the error.

**Comment by akemitakagi** [comment]
I am not sure what you guys are looking at.
Would you mind sending me the screenshot of two error/warning messages?

Thanks!

On 23 June 2015 at 17:13, Simon Hildrew notifications@github.com wrote:

> I'm with @robinedman https://github.com/robinedman! The fact that the
> message says 'error' but is a warning.
> 
> Can I clarify if the top one is the old one and the bottom is the new one?
> Or is the top and error and the bottom a warning? If so - I find the
> pastel/solid colour choices for the two a little weird. The warning is more
> dramatic than the error.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/tools-components/pull/33#issuecomment-114560050
> .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by jamespamplin** [comment]
RIP tools-components.

**Pull request closed without merging**
