### PR TITLE
Utils

### PR DESCRIPTION
**Pull request by cutandpastey**
This PR introduces utils needed for the restorer build it specifically adds:
- Loading Bars directive
- `safeApply` for dealing with the `$digest` cycle.
- Base Model
- Base Collection
- Small `CSS` fixes

### CODE REVIEW

**Comment by robinedman** [comment]
:+1:

**Comment by jamespamplin** [comment]
`lib/icons/.DS_Store`

**Comment by cutandpastey** [comment]
@jamespamplin its been removed, right?

**Comment by jamespamplin** [comment]
yes please :)

**Comment by cutandpastey** [comment]
No, I mean: It was removed in the PR.

**Comment by jamespamplin** [comment]
Ohhh sorry - my colour blindness failed me. Stupid ux

**Pull request merged**
